### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'EfficientNet' object has no attribute 'act_fn'

### ISSUE THREAD

**Issue by satya-panda** [thuyngch/Iris-Recognition-PyTorch#10]
Hi,
I downloaded the pre-trained weights and tried to run the setup by command:: 
python visualize.py --image IMG_0871.JPG  --config configs/mmu2_b0.json  --weight ./models/mmu2_b0.pth --use-cuda

getting error as ::
torch.nn.modules.module.ModuleAttributeError: 'EfficientNet' object has no attribute 'act_fn'

Stacktrace==

Traceback (most recent call last):
  File "visualize.py", line 194, in <module>
    mask = grad_cam(input, index=None)
  File "visualize.py", line 119, in __call__
    features, output = self.extractor(input)
  File "visualize.py", line 94, in __call__
    target_activations, output  = self.feature_extractor(x)
  File "visualize.py", line 69, in __call__
    x = self.model.act_fn(x, inplace=True)
  File "D:\project\iris\lib\site-packages\torch\nn\modules\module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'EfficientNet' object has no attribute 'act_fn'

Is this because of my environment as I have latest torch version::
torch==1.6.0+cpu
As i see in the code that, code handles both cpu and Gpu variant.

Please let me know your feedback. Thanks a lot :)

**Comment by hzli-ucas** [comment]
It has nothing to do with the torch version. This error is related with the architecture of 'EfficientNet', guess they (the 'timm' module, where the EfficientNet is defined) had modified the network structure.
You can run the following python code to check the structure of EfficientNet:
```
import timm
model = timm.create_model("efficientnet_b0")
print(model)
```
It's something like EfficientNet((conv_stem)...(bn1)...(act1)...(blocks)...(conv_head)...(bn2)...(act2)...).
Compare it with where the error occurs

> File "visualize.py", line 69, in call
> x = self.model.act_fn(x, inplace=True)

find the name 'act_fn' above does not match 'act1' in EfficientNet structure, there comes the error.
Here is the solution:
Change the two sentence
> x = self.model.act_fn(x, inplace=True)

into
> x = self.model.act1(x)
> x = self.model.act2(x)

respectively. That should work.
